c_compiler:
  - gcc
c_compiler_version:
  - "9"
cdt_name:
  - cos7
channel_sources:
  - pychaste
  - conda-forge
channel_targets:
  - pychaste main
cxx_compiler:
  - gxx
cxx_compiler_version:
  - "9"
docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64
fortran_compiler:
  - gfortran
fortran_compiler_version:
  - "9"
pin_run_as_build:
  xercesc:
    min_pin: x
    max_pin: x
target_platform:
  - linux-64
xercesc:
  - "3.0.0"
zip_keys:
  - - c_compiler_version
    - cxx_compiler_version
    - fortran_compiler_version
