boostcpp:
  - ">=1.68,<1.76"
cdt_name:
  - cos7
channel_sources:
  - pychaste
  - conda-forge
channel_targets:
  - pychaste main
cxx_compiler:
  - gxx
cxx_compiler_version:
  - "11"
docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64
fortran_compiler:
  - gfortran
fortran_compiler_version:
  - "11"
hdf5:
  - ">=1.10,<1.14"
metis:
  - ">=4"
mpich:
  - ">=3"
parmetis:
  - ">=4"
petsc:
  - ">=3.12,<3.19"
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
  - 3.8.* *_cpython
sundials:
  - ">=3.0,<6.0"
vtk:
  - "7.1.1"
xercesc:
  - ">=3"
target_platform:
  - linux-64
zip_keys:
  - - cxx_compiler_version
    - fortran_compiler_version
